sentiment_analysis_project/project_essentials/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
# from . import sent_app

urlpatterns = [
    # The line `from . import sent_app` in the URL configuration file is importing the `sent_app` module
    # from the current package or directory. This allows you to include the URLs defined in the `sent_app`
    # module in the main URL configuration of your Django project. By using `include("sent_app.urls")` in
    # the urlpatterns list, you are including the URLs defined in the `sent_app.urls` file in the main URL
    # patterns of your project. This helps in organizing and modularizing your URL configurations in
    # Django.
    path('admin/', admin.site.urls),
    path('sent_ana/', include("sent_app.urls")),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sentiment_analysis_project/py_app_files/urls.py
from django.contrib import admin
from django.urls import path
from sent_app import views

app_name="sent_app"

urlpatterns=[
    path('admin/',admin.site.urls),
    path("",views.index,name="index"),
    path("sentiment/",views.sentiment,name="sentiment"),
    path("404/",views.error_page,name="404"),
    path("buttons/",views.buttons,name="buttons"),
    path("cards/",views.cards,name="cards"),
    path("charts/",views.charts,name="charts"),
    path("forgot_password/",views.forgot_password,name="forgot_password"),
    path("register/",views.register,name="register"),
    path("login/",views.login,name="login"),
    path("tables/",views.tables,name="tables"),
    path("Save_data/",views.data_save,name="data_save"),
    path("utilities-animation/",views.utilities_animation,name="utilities-animation"),
    path("utilities-border/",views.utilities_border,name="utilities-border"),
    path("utilities-color/",views.utilities_color,name="utilities-color"),
    path("utilities-other/",views.utilities_other,name="utilities-other"),
    path("analyze_user_account/",views.get_user_account,name="analyze_user_account"),
    path("get_user_acc_comm/",views.get_user_account_comments,name="get_user_acc_comments"),
]

sentiment_analysis_project/py_app_files/models.py
from django.db import models

# Create your models here.
class Sentiment(models.Model):
    comment=models.TextField()
    positive=models.FloatField()
    negative=models.FloatField()
    neutral=models.FloatField()
    compound=models.FloatField()
    create_time=models.DateTimeField(auto_now_add=True)

class PostSentiment(models.Model):
    username=models.TextField()
    userid=models.TextField()
    postid=models.TextField()
    post_title=models.TextField()
    sentiment=models.TextField()
    sentiment_index=models.FloatField()
    total_comments=models.IntegerField()
    pos_sum=models.FloatField()
    neg_sum=models.FloatField()
    neu_sum=models.FloatField()
    total_positive=models.IntegerField()
    total_negative=models.IntegerField()
    total_neutral=models.IntegerField()

sentiment_analysis_project/py_app_files/views.py
import json
from django.shortcuts import render,redirect
from  sent_app.tasks import stream_and_save_comments,analyze_u_account
from .models import Sentiment,PostSentiment
from wordcloud import WordCloud
from io import BytesIO
import base64
import requests
import xlwt
# import numpy as np
from django.http import HttpResponse

def index(request):
    return render(request,"sent/index.html")

def buttons(request):
    return render(request,"sent/buttons.html")

def cards(request):
    return render(request,"sent/cards.html")

def error_page(request):
    return render(request,"sent/404.html")

def charts(request):
    # return render(request,"sent/charts.html")
    if request.method=="POST":
        url=request.POST.get("url")
        comments=stream_and_save_comments(url)
        if comments is None:
            return render(request,"sent/404.html")
        pos=0;neg=0;neu=0;total_comm=0;pos_sum=0;neg_sum=0;neu_sum=0
        overall_sentiments=[]
        print(type(comments))
        for comm in comments['comments_list']:
            # print(comments[ind]['compound'])
            if comm['sentiment'] == 'positive':
                pos_sum+=comm['positive']
                pos+=1
            elif comm['sentiment']  == 'negative':
                neg_sum+=comm['negative']
                neg+=1
            else:
                neu_sum+=comm['neutral']
                neu+=1
            total_comm+=1
            overall_sentiments.append(comm['comment'])
            # total_compound+=comments[ind]['compound']
        wc=WordCloud(width=800,height=400,max_words=600,background_color='white').generate(" ".join(overall_sentiments))
        buffer=BytesIO()
        wc.to_image().save(buffer,format='PNG')
        img_str=base64.b64encode(buffer.getvalue()).decode()
        pos_avg=pos_sum/pos if pos!=0 else 0
        neg_avg=neg_sum/neg if neg!=0 else 0
        neu_avg=neu_sum/neu if neu!=0 else 0
        sentiment_index=(pos-neg)/total_comm if total_comm!=0 else 0
        overall_sentiment=''
        if pos>neg and pos>neu:
            overall_sentiment='👍'
        elif neg>pos and neg>neu:
            overall_sentiment='👎'
        else:
            overall_sentiment='😐'
        title=comments['title']
        comm_count=comments['total_comments']
        chart_data={"post_img":comments['image'],"pos":pos,"neg":neg,"neu":neu,"total":overall_sentiment,"count":comm_count,'pos_avg':float(pos_avg),'neg_avg':float(neg_avg),'neu_avg':float(neu_avg),'sentiment_index':sentiment_index,'title':title}
        chart_data_json=json.dumps(chart_data)
        return render(request,"sent/charts.html",{"chart_data": chart_data,"chart_data_json":chart_data_json,"wordcloud_img":img_str})
        # return render(request,"sent/charts.html")
    return render(request,"sent/charts.html")

def get_user_account(request):
    if request.method=="POST":
        username=request.POST.get("username")
        analyze_u_account.delay(username)
        return redirect("sent_app:tables")
    return render(request,"sent/index.html")

def login(request):
    return render(request,"sent/login.html")

def data_save(request):
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="Sentiments_analysis.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Sheet1')

        # Sheet header, first row
        row_num = 0
        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        columns = ['Comment', 'Positive', 'Negative', 'Neutral', 'Compound'] 
        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        # Sheet body, subsequent rows
        font_style = xlwt.XFStyle()

        # Retrieving data from model
        data = Sentiment.objects.all() 
        for row in data:
            row_num += 1
            # Replace with your actual model fields
            ws.write(row_num, 0, row.comment, font_style) 
            ws.write(row_num, 1, row.positive, font_style)
            ws.write(row_num, 2, row.negative, font_style)
            ws.write(row_num, 3, row.neutral, font_style)
            ws.write(row_num, 4, row.compound, font_style)
        wb.save(response)
        return response

def forgot_password(request):
    return render(request,"sent/forgot-password.html")

def register(request):
    return render(request,"sent/register.html")

def tables(request):
    comments=Sentiment.objects.all().order_by("-create_time")[:100]
    if(comments.count()==0):
        return render(request,"sent/error.html")
    return render(request,"sent/tables.html",{"sentiments":comments})

def utilities_animation(request):
    return render(request,"sent/utilities-animation.html")

def utilities_border(request):
    return render(request,"sent/utilities-border.html")

def utilities_color(request):
    return render(request,"sent/utilities-color.html")

def utilities_other(request):
    return render(request,"sent/utilities-other.html")

def sentiment(request):
    stream_and_save_comments.delay()
    return redirect("sent_app:tables")
    
def get_user_account_comments(request):
    comms=PostSentiment.objects.all()[:100]
    if not comms:
        print("no comments " )
    return render(request,"sent/tables.html",{"post_sentiments":comms})

# def fetch_comments(request):
#     comments=Sentiment.objects.all().order_by("-create_time")
#     if(comments.count()==0):
#         return render(request,"sent/error.html")
#     return render(request,"sent/sentiment.html",{"sentiments":comments})

sentiment_analysis_project/templates/sent/boiler_plate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>   
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %} {% endblock %}</title>
    <!-- Custom fonts for this template-->
    <link href="{% static 'Vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom styles for this template-->
     <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" /> -->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'sent_app:index' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'sent_app:index' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="{% url 'sent_app:buttons' %}">Buttons</a>
                        <a class="collapse-item" href="{% url 'sent_app:cards' %}">Cards</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Utilities</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Utilities:</h6>
                        <a class="collapse-item" href="{% url 'sent_app:utilities-color' %}">Colors</a>
                        <a class="collapse-item" href="{% url 'sent_app:utilities-border' %}">Borders</a>
                        <a class="collapse-item" href="{% url 'sent_app:utilities-animation' %}">Animations</a>
                        <a class="collapse-item" href="{% url 'sent_app:utilities-other' %}">Other</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Login Screens:</h6>
                        <a class="collapse-item" href="{% url 'sent_app:login' %}">Login</a>
                        <a class="collapse-item" href="{% url 'sent_app:register' %}">Register</a>
                        <a class="collapse-item" href="{% url 'sent_app:forgot_password' %}">Forgot Password</a>
                        <div class="collapse-divider"></div>
                        <h6 class="collapse-header">Other Pages:</h6>
                        <a class="collapse-item" href="404.html">404 Page</a>
                        <a class="collapse-item" href="blank.html">Blank Page</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sent_app:charts' %}">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sent_app:tables' %}">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span></a>
            </li>
            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="{% static 'img/undraw_rocket.svg' %}" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div>

        </ul>
        <!-- End of Sidebar -->
         {% block content %}

         {% endblock %}


            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
    <!-- Step 2: Load libraries -->
    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-bar-demo.js' %}"></script>
    <!-- <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script> -->
{% block scripts %}{% endblock %}
</body>
</html>

sentiment_analysis_project/templates/sent/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

sentiment_analysis_project/templates/sent/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                id="exampleInputPassword" placeholder="Password">
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">Remember
                                                    Me</label>
                                            </div>
                                        </div>
                                        <a href="{% url 'sent_app:index' %}" class="btn btn-primary btn-user btn-block">
                                            Login
                                        </a>
                                        <hr>
                                        <a href="{% url 'sent_app:index' %}" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="{% url 'sent_app:index' %}" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'sent_app:forgot_password' %}">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="{% url 'sent_app:register' %}">Create an Account!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>

sentiment_analysis_project/templates/sent/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                            </div>
                            <form class="user">
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="text" class="form-control form-control-user" id="exampleFirstName"
                                            placeholder="First Name">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="text" class="form-control form-control-user" id="exampleLastName"
                                            placeholder="Last Name">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control form-control-user" id="exampleInputEmail"
                                        placeholder="Email Address">
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleInputPassword" placeholder="Password">
                                    </div>
                                    <div class="col-sm-6">
                                        <input type="password" class="form-control form-control-user"
                                            id="exampleRepeatPassword" placeholder="Repeat Password">
                                    </div>
                                </div>
                                <a href="login.html" class="btn btn-primary btn-user btn-block">
                                    Register Account
                                </a>
                                <hr>
                                <a href="index.html" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Register with Google
                                </a>
                                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                                </a>
                            </form>
                            <hr>
                            <div class="text-center">
                                <a class="small" href="{% url 'sent_app:forgot_password' %}">Forgot Password?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="{% url 'sent_app:login' %}">Already have an account? Login!</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>